@host=http://localhost:5000


// --------------------     Auth        ------------------- //

###
//          JWT Login           //
# @name login
POST {{host}}/login HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}


// -------------------      Create      ------------------- //

###
//      Create a new user       //
# @name register
POST {{host}}/user HTTP/1.1
Content-Type: application/json

{
    "username": "ghostsama",
    "password": "1234",
    "firstName": "ghost",
    "lastName": "sama",
    "email": "ghostsama@host.local",
    "age": 20
}


###
//    Create a second new user  //
POST {{host}}/user HTTP/1.1
Content-Type: application/json

{
    "username": "alincoln",
    "password": "sdfgs",
    "firstName": "abraham",
    "lastName": "lincoln",
    "email": "abrahamlincoln@host.local",
    "age": 30
}


// -------------------      Read        ------------------- //

###
//  Read the info using the username    //
GET {{host}}/user/ghostsama HTTP/1.1
Authorization: 
Authorization: Bearer {{login.response.body.token}}


###
//   Read the info of the all users    //
GET {{host}}/user HTTP/1.1
Authorization: Bearer {{login.response.body.token}}


// -------------------      Update      ------------------- //

###
//     Update partial info     //
PUT {{host}}/user/ghostsama HTTP/1.1
Authorization: Bearer {{login.response.body.token}}
Content-Type: application/json

{
    "firstName": "rin",
    "lastName": "tohsaka"
}


###
//     Update complete info     //
PUT {{host}}/user/ghostsama HTTP/1.1
Authorization: Bearer {{login.response.body.token}}
Content-Type: application/json

{
    "username": "eliones",
    "password": "lalala",
    "firstName": "elizabeth",
    "lastName": "liones",
    "email": "elizabethliones@host.local",
    "age": 21
}


// -------------------      Delete      ------------------- //

###
//      Delete user info        //
DELETE {{host}}/user/eliones HTTP/1.1
Authorization: Bearer {{login.response.body.token}}
