@host=http://localhost:5000


######################  Create  #######################
### Create a new user "ghostsama"
POST {{host}}/ HTTP/1.1
Content-Type: application/json

{
    "username": "ghostsama",
    "password": "1234",
    "firstName": "ghost",
    "lastName": "sama",
    "email": "ghostsama@host.local",
    "age": 20
}

### Create a second user "alincoln", only for tests
POST {{host}}/ HTTP/1.1
Content-Type: application/json

{
    "username": "alincoln",
    "password": "sdfgs",
    "firstName": "abraham",
    "lastName": "lincoln",
    "email": "abrahamlincoln@host.local",
    "age": 30
}


######################  Read  #########################
### Read user info using the username
GET {{host}}/ghostsama HTTP/1.1


### Read the info of the all users
GET {{host}}/ HTTP/1.1


######################  Update  #######################
### Update complete info
PUT {{host}}/ghostsama HTTP/1.1
Content-Type: application/json

{
    "username": "eliones",
    "password": "lalala",
    "firstName": "elizabeth",
    "lastName": "liones",
    "email": "elizabethliones@host.local",
    "age": 20
}

### Update partial info
PUT {{host}}/eliones HTTP/1.1
Content-Type: application/json

{
    "firstName": "rin",
    "lastName": "tohsaka"
}


######################  Delete  #######################
### Delete user info
DELETE {{host}}/eliones HTTP/1.1
